
logging:
  level:
    root: info
server:
  port: 8081

spring:
  cache:
    type: caffeine
    cache-names:
      - userCache
    caffeine:
      spec: maximumSize=1024,refreshAfterWrite=60s
#热部署生效
  devtools:
    restart:
      enabled: true

#这个是用来远程连接的
#arthas:
#  agent-id: hsehdfsfghhwertyfad
  #tunnel-server: ws://127.0.0.1:7777/ws
