server:
  port: 3001
eureka:
  instance:
    preferIpAddress: true #将自己的ip注册到eureka服务器上去
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka  # 注册到 eureka
spring:
  application:
    name: single-provider  # 应用程序名称，后面会在消费者中用到