spring:
  application:
    name: consul-client
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
#      discovery:
#        healthCheckPath: /xxh
#        healthCheckInterval: 5s
      discovery:
        tags: foo=bar, baz