
logging:
  level:
    root: info
server:
  port: 8081

spring:
  cache:
    type: caffeine
    cache-names:
      - userCache
    caffeine:
      spec: maximumSize=1024,refreshAfterWrite=60s
#热部署生效
  devtools:
    restart:
      enabled: true
